import type { ModuleConfig, Role } from './types';

export const roles: Role[] = ['admin', 'staff', 'vet'];

export const permissions: Record<string, Role[]> = {
  dashboard: ['admin', 'staff', 'vet'],
  tasks: ['admin', 'staff', 'vet'],
  pigs: ['admin', 'vet'],
  pens: ['admin', 'staff'],
  weights: ['admin', 'staff', 'vet'],
  breeding: ['admin', 'vet'],
  health: ['admin', 'vet'],
  feeding: ['admin', 'staff'],
  'feed-inventory': ['admin', 'staff'],
  sales: ['admin'],
  expenses: ['admin'],
  reports: ['admin', 'vet'],
  users: ['admin'],
  breeds: ['admin'],
};

const active = ['active', 'inactive'];
const pigStatuses = ['active', 'sold', 'deceased', 'transferred'];

export const modules: ModuleConfig[] = [
  {
    key: 'pigs',
    title: 'Pig Inventory',
    table: 'pigs',
    roles: permissions.pigs,
    icon: 'Rows3',
    description: 'Individual animal records, assignment, source, status, and weight.',
    columns: ['pig_tag', 'pig_type', 'gender', 'pen_id', 'date_of_birth', 'current_weight', 'status'],
    searchKeys: ['pig_tag', 'pig_type', 'status'],
    softDelete: { field: 'status', value: 'deceased' },
    defaultValues: { status: 'active', source: 'born_on_farm', purchase_price: 0 },
    fields: [
      { key: 'pig_tag', label: 'Pig tag', required: true },
      { key: 'breed_id', label: 'Breed ID', type: 'number' },
      { key: 'gender', label: 'Gender', type: 'select', required: true, options: ['male', 'female'] },
      { key: 'pig_type', label: 'Type', type: 'select', required: true, options: ['boar', 'sow', 'gilt', 'grower', 'finisher', 'piglet'] },
      { key: 'pen_id', label: 'Pen ID', type: 'number' },
      { key: 'date_of_birth', label: 'Date of birth', type: 'date' },
      { key: 'source', label: 'Source', type: 'select', options: ['born_on_farm', 'purchased'] },
      { key: 'purchase_price', label: 'Purchase price', type: 'number' },
      { key: 'birth_weight', label: 'Birth weight kg', type: 'number' },
      { key: 'current_weight', label: 'Current weight kg', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: pigStatuses },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'pens',
    title: 'Pens',
    table: 'pens',
    roles: permissions.pens,
    icon: 'Warehouse',
    description: 'Housing capacity, type, and maintenance status.',
    columns: ['pen_number', 'pen_type', 'capacity', 'current_count', 'status'],
    searchKeys: ['pen_number', 'pen_type', 'status'],
    defaultValues: { status: 'active', capacity: 10 },
    softDelete: { field: 'status', value: 'inactive' },
    fields: [
      { key: 'pen_number', label: 'Pen number', required: true },
      { key: 'pen_type', label: 'Type', type: 'select', required: true, options: ['nursery', 'grower', 'finisher', 'farrowing', 'boar', 'gilt', 'isolation'] },
      { key: 'capacity', label: 'Capacity', type: 'number', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'maintenance', 'inactive'] },
    ],
  },
  {
    key: 'weights',
    title: 'Weight Records',
    table: 'weight_records',
    roles: permissions.weights,
    icon: 'Scale',
    description: 'Weight history and growth tracking.',
    columns: ['pig_id', 'weight_kg', 'recorded_date', 'age_days', 'notes'],
    searchKeys: ['pig_id', 'recorded_date'],
    defaultValues: { recorded_date: new Date().toISOString().slice(0, 10) },
    fields: [
      { key: 'pig_id', label: 'Pig ID', type: 'number', required: true },
      { key: 'weight_kg', label: 'Weight kg', type: 'number', required: true },
      { key: 'recorded_date', label: 'Date', type: 'date', required: true },
      { key: 'age_days', label: 'Age days', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'breeding',
    title: 'Breeding',
    table: 'breeding_records',
    roles: permissions.breeding,
    icon: 'HeartPulse',
    description: 'Breeding, expected farrowing, litter, and weaning records.',
    columns: ['sow_id', 'boar_id', 'breeding_date', 'expected_farrowing', 'status'],
    searchKeys: ['sow_id', 'boar_id', 'status'],
    defaultValues: { breeding_type: 'natural', status: 'bred' },
    fields: [
      { key: 'sow_id', label: 'Sow ID', type: 'number', required: true },
      { key: 'boar_id', label: 'Boar ID', type: 'number', required: true },
      { key: 'breeding_date', label: 'Breeding date', type: 'date', required: true },
      { key: 'breeding_type', label: 'Type', type: 'select', options: ['natural', 'artificial_insemination'] },
      { key: 'expected_farrowing', label: 'Expected farrowing', type: 'date' },
      { key: 'actual_farrowing', label: 'Actual farrowing', type: 'date' },
      { key: 'total_born', label: 'Total born', type: 'number' },
      { key: 'born_alive', label: 'Born alive', type: 'number' },
      { key: 'stillborn', label: 'Stillborn', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['bred', 'confirmed_pregnant', 'farrowed', 'weaned', 'failed'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'health',
    title: 'Health Records',
    table: 'health_records',
    roles: permissions.health,
    icon: 'ShieldPlus',
    description: 'Vaccinations, treatments, deworming, diagnosis, and cost.',
    columns: ['record_type', 'health_date', 'pig_id', 'pen_id', 'medicine_name', 'next_due_date'],
    searchKeys: ['record_type', 'medicine_name', 'diagnosis'],
    defaultValues: { route: 'injection', health_date: new Date().toISOString().slice(0, 10), cost: 0 },
    fields: [
      { key: 'pig_id', label: 'Pig ID', type: 'number' },
      { key: 'pen_id', label: 'Pen ID', type: 'number' },
      { key: 'record_type', label: 'Type', type: 'select', required: true, options: ['vaccination', 'treatment', 'deworming', 'vitamin', 'diagnosis', 'surgery'] },
      { key: 'health_date', label: 'Date', type: 'date', required: true },
      { key: 'diagnosis', label: 'Diagnosis', type: 'textarea' },
      { key: 'medicine_name', label: 'Medicine' },
      { key: 'dosage', label: 'Dosage' },
      { key: 'route', label: 'Route', type: 'select', options: ['oral', 'injection', 'topical', 'feed'] },
      { key: 'administered_by', label: 'Administered by' },
      { key: 'next_due_date', label: 'Next due', type: 'date' },
      { key: 'cost', label: 'Cost', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'feeding',
    title: 'Feeding',
    table: 'feeding_records',
    roles: permissions.feeding,
    icon: 'Utensils',
    description: 'Daily feed use by pen or individual animal.',
    columns: ['feeding_date', 'feeding_time', 'feed_type_id', 'pen_id', 'pig_id', 'quantity_kg'],
    searchKeys: ['feeding_date', 'feeding_time', 'feed_type_id'],
    defaultValues: { feeding_date: new Date().toISOString().slice(0, 10), feeding_time: 'morning' },
    fields: [
      { key: 'pen_id', label: 'Pen ID', type: 'number' },
      { key: 'pig_id', label: 'Pig ID', type: 'number' },
      { key: 'feed_type_id', label: 'Feed type ID', type: 'number', required: true },
      { key: 'feeding_date', label: 'Date', type: 'date', required: true },
      { key: 'feeding_time', label: 'Time', type: 'select', options: ['morning', 'noon', 'afternoon', 'evening'] },
      { key: 'quantity_kg', label: 'Quantity kg', type: 'number', required: true },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'feed-inventory',
    title: 'Feed Inventory',
    table: 'feed_inventory',
    roles: permissions['feed-inventory'],
    icon: 'Package',
    description: 'Current stock level and reorder threshold by feed type.',
    columns: ['feed_type_id', 'quantity_kg', 'minimum_stock_kg', 'last_restocked'],
    searchKeys: ['feed_type_id'],
    defaultValues: { quantity_kg: 0, minimum_stock_kg: 50 },
    fields: [
      { key: 'feed_type_id', label: 'Feed type ID', type: 'number', required: true },
      { key: 'quantity_kg', label: 'Quantity kg', type: 'number', required: true },
      { key: 'minimum_stock_kg', label: 'Minimum stock kg', type: 'number' },
      { key: 'last_restocked', label: 'Last restocked', type: 'date' },
    ],
  },
  {
    key: 'sales',
    title: 'Sales',
    table: 'sales_records',
    roles: permissions.sales,
    icon: 'ReceiptText',
    description: 'Pig sales, buyer details, payment state, and revenue.',
    columns: ['sale_date', 'pig_id', 'sale_type', 'live_weight_kg', 'total_amount', 'payment_status'],
    searchKeys: ['buyer_name', 'payment_status', 'sale_type'],
    defaultValues: { sale_date: new Date().toISOString().slice(0, 10), sale_type: 'live_weight', payment_status: 'paid', amount_paid: 0 },
    fields: [
      { key: 'sale_date', label: 'Sale date', type: 'date', required: true },
      { key: 'pig_id', label: 'Pig ID', type: 'number', required: true },
      { key: 'sale_type', label: 'Type', type: 'select', options: ['live_weight', 'dressed', 'breeding_stock', 'weaner'] },
      { key: 'buyer_name', label: 'Buyer name' },
      { key: 'buyer_contact', label: 'Buyer contact' },
      { key: 'live_weight_kg', label: 'Live weight kg', type: 'number' },
      { key: 'dressed_weight_kg', label: 'Dressed weight kg', type: 'number' },
      { key: 'price_per_kg', label: 'Price per kg', type: 'number', required: true },
      { key: 'total_amount', label: 'Total amount', type: 'number', required: true },
      { key: 'payment_status', label: 'Payment', type: 'select', options: ['paid', 'partial', 'pending'] },
      { key: 'amount_paid', label: 'Amount paid', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'expenses',
    title: 'Expenses',
    table: 'expenses',
    roles: permissions.expenses,
    icon: 'CircleDollarSign',
    description: 'Farm costs by category, vendor, receipt, and notes.',
    columns: ['expense_date', 'category', 'description', 'amount', 'vendor'],
    searchKeys: ['description', 'category', 'vendor'],
    defaultValues: { expense_date: new Date().toISOString().slice(0, 10), category: 'feed' },
    fields: [
      { key: 'expense_date', label: 'Expense date', type: 'date', required: true },
      { key: 'category', label: 'Category', type: 'select', required: true, options: ['feed', 'medicine', 'utilities', 'labor', 'equipment', 'maintenance', 'other'] },
      { key: 'description', label: 'Description', required: true },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'vendor', label: 'Vendor' },
      { key: 'receipt_number', label: 'Receipt number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'tasks',
    title: 'Tasks',
    table: 'tasks',
    roles: permissions.tasks,
    icon: 'ListTodo',
    description: 'Farm reminders and assigned work.',
    columns: ['task_title', 'task_type', 'due_date', 'priority', 'status', 'assigned_to'],
    searchKeys: ['task_title', 'task_type', 'priority', 'status'],
    defaultValues: { status: 'pending', priority: 'medium', task_type: 'other' },
    softDelete: { field: 'status', value: 'cancelled' },
    fields: [
      { key: 'task_title', label: 'Task title', required: true },
      { key: 'task_type', label: 'Type', type: 'select', options: ['feeding', 'vaccination', 'deworming', 'weighing', 'cleaning', 'breeding', 'other'] },
      { key: 'due_date', label: 'Due date', type: 'date', required: true },
      { key: 'pig_id', label: 'Pig ID', type: 'number' },
      { key: 'pen_id', label: 'Pen ID', type: 'number' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'urgent'] },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'completed', 'overdue', 'cancelled'] },
      { key: 'assigned_to', label: 'Assigned user ID', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    key: 'breeds',
    title: 'Breeds',
    table: 'pig_breeds',
    roles: permissions.breeds,
    icon: 'Tags',
    description: 'Breed reference data for animal records.',
    columns: ['breed_name', 'avg_gestation_days', 'avg_litter_size', 'description'],
    searchKeys: ['breed_name', 'description'],
    defaultValues: { avg_gestation_days: 114, avg_litter_size: 10 },
    fields: [
      { key: 'breed_name', label: 'Breed name', required: true },
      { key: 'avg_gestation_days', label: 'Gestation days', type: 'number' },
      { key: 'avg_litter_size', label: 'Avg litter size', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    key: 'users',
    title: 'Users',
    table: 'profiles',
    roles: permissions.users,
    icon: 'Users',
    description: 'Staff profiles and access roles. Create auth users in Supabase first, then maintain the profile here.',
    columns: ['username', 'full_name', 'role', 'email', 'contact', 'status'],
    searchKeys: ['username', 'full_name', 'email', 'role'],
    defaultValues: { role: 'staff', status: 'active' },
    softDelete: { field: 'status', value: 'inactive' },
    fields: [
      { key: 'id', label: 'Auth user UUID', required: true },
      { key: 'username', label: 'Username', required: true },
      { key: 'full_name', label: 'Full name', required: true },
      { key: 'role', label: 'Role', type: 'select', options: roles },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'contact', label: 'Contact' },
      { key: 'status', label: 'Status', type: 'select', options: active },
    ],
  },
];

export const navGroups = [
  { label: 'Overview', keys: ['dashboard', 'tasks'] },
  { label: 'Pig Management', keys: ['pigs', 'pens', 'weights', 'breeding'] },
  { label: 'Health & Feeding', keys: ['health', 'feeding', 'feed-inventory'] },
  { label: 'Finance', keys: ['sales', 'expenses', 'reports'] },
  { label: 'Admin', keys: ['users', 'breeds'] },
];
