-- PigTrack Pro Supabase schema
-- Run this in the Supabase SQL editor before deploying the PWA.

create extension if not exists pgcrypto;

do $$ begin create type app_role as enum ('admin','staff','vet'); exception when duplicate_object then null; end $$;
do $$ begin create type record_status as enum ('active','inactive','sold','deceased','transferred'); exception when duplicate_object then null; end $$;
do $$ begin create type pen_status as enum ('active','maintenance','inactive'); exception when duplicate_object then null; end $$;
do $$ begin create type task_status as enum ('pending','completed','overdue','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type payment_status as enum ('paid','partial','pending'); exception when duplicate_object then null; end $$;

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  full_name text not null,
  role app_role not null default 'staff',
  email text,
  contact text,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists pig_breeds (
  id bigint generated by default as identity primary key,
  breed_name text not null,
  description text,
  avg_gestation_days integer default 114,
  avg_litter_size integer default 10,
  created_at timestamptz not null default now()
);

create table if not exists pens (
  id bigint generated by default as identity primary key,
  pen_number text not null unique,
  pen_type text not null,
  capacity integer not null default 10,
  current_count integer default 0,
  description text,
  status pen_status default 'active',
  created_at timestamptz not null default now()
);

create table if not exists pigs (
  id bigint generated by default as identity primary key,
  pig_tag text not null unique,
  breed_id bigint references pig_breeds(id) on delete set null,
  gender text not null check (gender in ('male','female')),
  pig_type text not null check (pig_type in ('boar','sow','gilt','grower','finisher','piglet')),
  pen_id bigint references pens(id) on delete set null,
  date_of_birth date,
  source text default 'born_on_farm',
  purchase_price numeric(10,2) default 0,
  mother_id bigint references pigs(id) on delete set null,
  father_id bigint references pigs(id) on delete set null,
  birth_weight numeric(6,2),
  current_weight numeric(6,2),
  status record_status default 'active',
  notes text,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists feed_types (
  id bigint generated by default as identity primary key,
  feed_name text not null,
  feed_category text not null,
  brand text,
  protein_percent numeric(5,2),
  price_per_kg numeric(8,2),
  unit text default 'kg',
  description text,
  status text default 'active',
  created_at timestamptz not null default now()
);

create table if not exists feed_inventory (
  id bigint generated by default as identity primary key,
  feed_type_id bigint not null references feed_types(id) on delete cascade,
  quantity_kg numeric(10,2) not null default 0,
  minimum_stock_kg numeric(10,2) default 50,
  last_restocked date
);

create table if not exists feeding_records (
  id bigint generated by default as identity primary key,
  pen_id bigint references pens(id) on delete set null,
  pig_id bigint references pigs(id) on delete set null,
  feed_type_id bigint not null references feed_types(id) on delete cascade,
  feeding_date date not null,
  feeding_time text default 'morning',
  quantity_kg numeric(8,2) not null,
  notes text,
  recorded_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists weight_records (
  id bigint generated by default as identity primary key,
  pig_id bigint not null references pigs(id) on delete cascade,
  weight_kg numeric(6,2) not null,
  recorded_date date not null,
  age_days integer,
  notes text,
  recorded_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists health_records (
  id bigint generated by default as identity primary key,
  pig_id bigint references pigs(id) on delete cascade,
  pen_id bigint references pens(id) on delete set null,
  record_type text not null,
  health_date date not null,
  diagnosis text,
  medicine_name text,
  dosage text,
  route text default 'injection',
  administered_by text,
  next_due_date date,
  cost numeric(10,2) default 0,
  notes text,
  recorded_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists breeding_records (
  id bigint generated by default as identity primary key,
  sow_id bigint not null references pigs(id) on delete cascade,
  boar_id bigint not null references pigs(id) on delete cascade,
  breeding_date date not null,
  breeding_type text default 'natural',
  expected_farrowing date,
  actual_farrowing date,
  total_born integer default 0,
  born_alive integer default 0,
  stillborn integer default 0,
  mummified integer default 0,
  litter_weight_kg numeric(8,2),
  weaning_date date,
  weaned_count integer default 0,
  status text default 'bred',
  notes text,
  recorded_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists mortality_records (
  id bigint generated by default as identity primary key,
  pig_id bigint not null references pigs(id) on delete cascade,
  death_date date not null,
  cause_of_death text,
  death_category text default 'unknown',
  estimated_value numeric(10,2) default 0,
  notes text,
  recorded_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists sales_records (
  id bigint generated by default as identity primary key,
  sale_date date not null,
  pig_id bigint not null references pigs(id) on delete cascade,
  sale_type text default 'live_weight',
  buyer_name text,
  buyer_contact text,
  live_weight_kg numeric(8,2),
  dressed_weight_kg numeric(8,2),
  price_per_kg numeric(8,2) not null,
  total_amount numeric(12,2) not null,
  payment_status payment_status default 'paid',
  amount_paid numeric(12,2) default 0,
  notes text,
  recorded_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  expense_date date not null,
  category text not null,
  description text not null,
  amount numeric(10,2) not null,
  vendor text,
  receipt_number text,
  notes text,
  recorded_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  task_title text not null,
  task_type text default 'other',
  due_date date not null,
  pig_id bigint references pigs(id) on delete set null,
  pen_id bigint references pens(id) on delete set null,
  priority text default 'medium',
  status task_status default 'pending',
  assigned_to uuid references profiles(id) on delete set null,
  notes text,
  created_by uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create or replace function touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists pigs_touch_updated_at on pigs;
create trigger pigs_touch_updated_at before update on pigs for each row execute function touch_updated_at();

create or replace function refresh_pen_counts()
returns trigger language plpgsql as $$
begin
  update pens set current_count = (
    select count(*) from pigs where pigs.pen_id = pens.id and pigs.status = 'active'
  );
  return null;
end $$;

drop trigger if exists pigs_refresh_pen_counts on pigs;
create trigger pigs_refresh_pen_counts after insert or update or delete on pigs for each statement execute function refresh_pen_counts();

create or replace function current_role()
returns app_role language sql stable security definer as $$
  select role from profiles where id = auth.uid()
$$;

create or replace function can_read_module(module text)
returns boolean language plpgsql stable security definer as $$
declare r app_role;
begin
  select current_role() into r;
  if r = 'admin' then return true; end if;
  if module in ('tasks','weight_records') and r in ('staff','vet') then return true; end if;
  if module in ('pens','feeding_records','feed_inventory') and r = 'staff' then return true; end if;
  if module in ('pigs','health_records','breeding_records','reports') and r = 'vet' then return true; end if;
  return false;
end $$;

alter table profiles enable row level security;
alter table pig_breeds enable row level security;
alter table pens enable row level security;
alter table pigs enable row level security;
alter table feed_types enable row level security;
alter table feed_inventory enable row level security;
alter table feeding_records enable row level security;
alter table weight_records enable row level security;
alter table health_records enable row level security;
alter table breeding_records enable row level security;
alter table mortality_records enable row level security;
alter table sales_records enable row level security;
alter table expenses enable row level security;
alter table tasks enable row level security;

create policy "profiles own read or admin" on profiles for select using (id = auth.uid() or current_role() = 'admin');
create policy "profiles admin write" on profiles for all using (current_role() = 'admin') with check (current_role() = 'admin');

create policy "admin all pig_breeds" on pig_breeds for all using (current_role() = 'admin') with check (current_role() = 'admin');
create policy "read pig_breeds" on pig_breeds for select using (current_role() in ('admin','staff','vet'));

create policy "pens access" on pens for all using (current_role() in ('admin','staff')) with check (current_role() in ('admin','staff'));
create policy "pigs access" on pigs for all using (current_role() in ('admin','vet')) with check (current_role() in ('admin','vet'));
create policy "feed types read" on feed_types for select using (current_role() in ('admin','staff','vet'));
create policy "feed types admin staff" on feed_types for all using (current_role() in ('admin','staff')) with check (current_role() in ('admin','staff'));
create policy "feed inventory access" on feed_inventory for all using (current_role() in ('admin','staff')) with check (current_role() in ('admin','staff'));
create policy "feeding access" on feeding_records for all using (current_role() in ('admin','staff')) with check (current_role() in ('admin','staff'));
create policy "weights access" on weight_records for all using (current_role() in ('admin','staff','vet')) with check (current_role() in ('admin','staff','vet'));
create policy "health access" on health_records for all using (current_role() in ('admin','vet')) with check (current_role() in ('admin','vet'));
create policy "breeding access" on breeding_records for all using (current_role() in ('admin','vet')) with check (current_role() in ('admin','vet'));
create policy "mortality access" on mortality_records for all using (current_role() in ('admin','vet')) with check (current_role() in ('admin','vet'));
create policy "sales admin" on sales_records for all using (current_role() = 'admin') with check (current_role() = 'admin');
create policy "expenses admin" on expenses for all using (current_role() = 'admin') with check (current_role() = 'admin');
create policy "tasks access" on tasks for all using (current_role() in ('admin','staff','vet')) with check (current_role() in ('admin','staff','vet'));

insert into pig_breeds (breed_name, description, avg_gestation_days, avg_litter_size) values
('Landrace', 'Long body, large lop ears, white skin. Excellent mothering ability.', 114, 12),
('Large White', 'White, upright ears, dished face. Good feed conversion.', 115, 11),
('Duroc', 'Red-brown color, drooping ears. Fast growth rate.', 114, 9),
('Hampshire', 'Black with white belt. Lean meat quality.', 114, 10),
('Berkshire', 'Black with white points. Premium pork quality.', 114, 9),
('Native/Bisaya', 'Local Philippine breed. Hardy and disease-resistant.', 114, 8)
on conflict do nothing;

insert into pens (pen_number, pen_type, capacity, description) values
('PEN-001', 'farrowing', 5, 'Farrowing crates for sows'),
('PEN-002', 'nursery', 30, 'Piglets 0-8 weeks'),
('PEN-003', 'grower', 20, 'Growing pigs 8-16 weeks'),
('PEN-004', 'finisher', 20, 'Finishing pigs 16+ weeks'),
('PEN-005', 'boar', 3, 'Breeding boars'),
('PEN-006', 'gilt', 10, 'Replacement gilts'),
('PEN-007', 'isolation', 5, 'Sick/new animal isolation')
on conflict (pen_number) do nothing;

insert into feed_types (feed_name, feed_category, brand, protein_percent, price_per_kg) values
('Starter Mash', 'starter', 'UFC', 22, 45),
('Grower Pellet', 'grower', 'UFC', 18, 38),
('Finisher Pellet', 'finisher', 'UFC', 16, 35),
('Sow & Gilt Feed', 'sow', 'Vitarich', 16.5, 40),
('Boar Maintainer', 'boar', 'Vitarich', 17, 42),
('Pre-Starter Crumble', 'starter', 'Integra', 23, 55)
on conflict do nothing;
